---
{{- include "psps" . }}
---
{{- include "cluster" . }}
---
{{- include "gcp-cluster" . }}
---
{{ if .Values.bastion.enabled }}
{{- include "bastion" . }}
---
{{ end }}
{{- include "control-plane" . }}
---
{{- include "machine-deployments" . }}
