---
{{- include "coredns" . }}
---
{{- include "psps" . }}
---
{{- include "cluster" . }}
---
{{- include "gcp-cluster" . }}
---
{{- include "bastion" . }}
---
{{- include "control-plane" . }}
---
{{- include "machine-deployments" . }}
