{{- include "shared.default-psps" . }}
---
{{- include "shared.coredns-adopter" . }}
---
{{- include "cluster" . }}
---
{{- include "gcp-cluster" . }}
---
{{- include "control-plane" . }}
---
{{- include "machine-deployments" . }}
