version: 2.1
orbs:
  architect: giantswarm/architect@4.25.0

jobs:
  acceptance-tests:
    executor: architect/machine
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - checkout
      - architect/machine-install-go
      - architect/integration-test-install-tools:
          apptestctl-version: v0.14.1
          helm-version: v3.8.2
          kubernetes-version: v1.21.1
      - run:
          name: "Run acceptance tests"
          command: make test-acceptance

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - acceptance-tests:
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push cluster-gcp chart"
          app_catalog: "cluster-catalog"
          app_catalog_test: "cluster-test-catalog"
          chart: "cluster-gcp"
          persist_chart_archive: true
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
