---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-shared-test-pod
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: cluster-shared-test-pod
  namespace: default
spec:
  serviceAccountName: default
  containers:
    - name: kubectl
      image: "giantswarm/docker-kubectl:1.23.3"
      command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset
          
          # piping stderr to stdout means kubectl's errors are surfaced
          # in the pod's logs.
          
          kubectl apply -f /etc/config 2>&1
      volumeMounts:
        - name: configmap-manifests
          mountPath: /etc/config
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
  volumes:
    - name: configmap-manifests
      configMap:
        name: test-psps
  restartPolicy: Never
