apiVersion: v2
name: cluster-gcp
description: A helm chart for creating Cluster API clusters with the GCP infrastructure provider (CAPG).
type: application
version: [[ .Version ]]
annotations:
  application.giantswarm.io/team: "phoenix"
restrictions:
  compatibleProviders:
    - gcp
dependencies:
- name: cluster-shared
  version: "0.4.1-d7ca09fa82cb57c345dd1d33f03535d6421bdd5d"
  repository: "https://giantswarm.github.io/cluster-test-catalog"
