apiVersion: v2
name: cluster-gcp
description: A helm chart for creating Cluster API clusters with the GCP infrastructure provider (CAPG).
type: application
version: [[ .Version ]]
annotations:
  application.giantswarm.io/team: "hydra"
  application.giantswarm.io/app-type: "cluster"
restrictions:
  compatibleProviders:
    - gcp
dependencies:
- name: cluster-shared
  version: "0.6.4"
  repository: "https://giantswarm.github.io/cluster-catalog"
icon: https://s.giantswarm.io/app-icons/gcp/1/light.svg
