clusterName: "test"  # Name of cluster. Used as base name for all cluster resources in the management cluster.
clusterDescription: ""  # Cluster description used in metadata.
organization: ""  # Organization in which to create the cluster.
baseDomain: ""  # Customer base domain, generally of the form "<customer codename>.gigantic.io".
kubernetesVersion: 1.23.13
ubuntuImageVersion: "2204"

vmImageBase: "https://www.googleapis.com/compute/v1/projects/giantswarm-vm-images/global/images/"

gcp:
  region: "europe-west3"
  project: ""  # GCP Project where the cluster will be created.
  failureDomains:  # These will be the failure domains used for the control plane machines.
    - europe-west3-a
    - europe-west3-b
    - europe-west3-c

network:
  # proxySubnetCidr
  # CIDR to be used for the proxy subnet. If empty, the subnet won't be created.
  # A proxy-only subnet must provide 64 or more IP addresses. This corresponds to a prefix length of /26 or shorter.
  # The recommended subnet size is /23 (512 proxy-only addresses).
  proxySubnetCidr: ""

  # nodeSubnetCidr
  # CIDR to be used for the subnet where VMs will be created.
  nodeSubnetCidr: "192.168.0.0/16"

  # podCidr
  # CIDRs for the pods. They need to be different than `nodeSubnetCidr`.
  podCidr:
    - "10.0.0.0/16"

  # serviceCIDR
  # CIDR for the kubernetes Services.
  serviceCIDR: 172.31.0.0/16

# A bastion host that will be used for SSH.
bastion:
  enabled: true
  instanceType: n1-standard-2
  replicas: 1
  allowlistSubnets: ""  # A comma separated list of cidrs that will have ssh access to the bastion hosts.

controlPlane:
  apiAllowlistSubnets: ""  # A comma separated list of cidrs that will have access to the kubernetes API.
  instanceType: n2-standard-4
  rootVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, the other only supported type is "pd-ssd"
  etcdVolume:
    sizeGB: 100
    diskType: "local-ssd"  # Override to allow etcd more IO operations
  containerdVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, other options are: ["pd-ssd"|"local-ssd"]
  kubeletVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, other options are: ["pd-ssd"|"local-ssd"]
  serviceAccount:
    email: "default"   # A service account used by the control-plane to set up LoadBalancer Services
    scopes:
    - "https://www.googleapis.com/auth/compute"
  etcd:
    imageRepository: "docker.io/giantswarm"
    imageTag: 3.5.4-0-k8s

# machineDeployments lets you configure the different nodepools that will be created.
machineDeployments:
- name: def00
  # The description is the name of the nodepool in GiantSwarm UIs. It's optional.
  # description:
  failureDomain: europe-west3-a
  instanceType: n2-standard-4
  replicas: 1
  rootVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, the other only supported type is "pd-ssd"
  containerdVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, other options are: ["pd-ssd"|"local-ssd"]
  kubeletVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, other options are: ["pd-ssd"|"local-ssd"]
  customNodeLabels: []
  customNodeTaints: []
    # - key: ""
    #   value: ""
    #   effect: "" # Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
  serviceAccount:  # A service account used by workloads using google SDK on this nodepool.
    email: "default"
    scopes:
      - "https://www.googleapis.com/auth/compute"
      - "https://www.googleapis.com/auth/ndev.clouddns.readwrite"
- name: def01
  # description:
  failureDomain: europe-west3-b
  instanceType: n2-standard-4
  replicas: 1
  rootVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, the other only supported type is "pd-ssd"
  containerdVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, other options are: ["pd-ssd"|"local-ssd"]
  kubeletVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, other options are: ["pd-ssd"|"local-ssd"]
  customNodeLabels: []
  customNodeTaints: []
    # - key: ""
    #   value: ""
    #   effect: "" # Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
  serviceAccount:  # A service account used by workloads using google SDK on this nodepool.
    email: "default"
    scopes:
      - "https://www.googleapis.com/auth/compute"
      - "https://www.googleapis.com/auth/ndev.clouddns.readwrite"
- name: def02
  # description:
  failureDomain: europe-west3-c
  instanceType: n2-standard-4
  replicas: 1
  rootVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, the other only supported type is "pd-ssd"
  containerdVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, other options are: ["pd-ssd"|"local-ssd"]
  kubeletVolume:
    sizeGB: 100
    diskType: "pd-ssd"  # "pd-standard" is the default one, other options are: ["pd-ssd"|"local-ssd"]
  customNodeLabels: []
  customNodeTaints: []
    # - key: ""
    #   value: ""
    #   effect: "" # Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
  serviceAccount:  # A service account used by workloads using google SDK on this nodepool.
    email: "default"
    scopes:
      - "https://www.googleapis.com/auth/compute"
      - "https://www.googleapis.com/auth/ndev.clouddns.readwrite"

sshSSOPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4cvZ01fLmO9cJbWUj7sfF+NhECgy+Cl0bazSrZX7sU vault-ca@vault.operations.giantswarm.io"

oidc:
  issuerUrl: ""
  caFile: ""
  clientId: ""
  usernameClaim: ""
  groupsClaim: ""

# Used by `cluster-shared` library chart
includeClusterResourceSet: true
kubectlImage:
  registry: quay.io
  name: giantswarm/kubectl
  tag: 1.23.5

# Used to force-recreate resources that use a hash suffix in their name.
# To use, set this to a random string to trigger new hash values to be generated.
hashSalt: ""
