clusterName: "test"  # Name of cluster. Used as base name for all cluster resources in the management cluster.
clusterDescription: "test"  # Cluster description used in metadata.
organization: "test"  # Organization in which to create the cluster.
baseDomain: ""  # Customer base domain, generally of the form "<customer codename>.gigantic.io".
kubernetesVersion: 1.20.10

gcp:
  baseImage: "https://www.googleapis.com/compute/v1/projects/capi-test-phoenix/global/images/cluster-api-ubuntu-1804-v1-20-10-1642604275"
  region: "europe-west3"
  project: "capi-test-phoenix"
  failureDomains:
    - europe-west3-a

network:
  autoCreateSubnetworks: true
  podCidr:
    - "192.168.0.0/16"
  serviceCIDR: 172.31.0.0/16

bastion:
  instanceType: n1-standard-2
  replicas: 1
  image: "https://www.googleapis.com/compute/v1/projects/capi-test-phoenix/global/images/cluster-api-ubuntu-1804-v1-20-10-1642604275"

controlPlane:
  instanceType: n2-standard-4
  replicas: 3  # Should be an odd number.
  rootVolumeSizeGB: 120
  serviceAccount:
    email: "default"  # A service account used by the control-plane to set up LoadBalancer Services
    scopes:
    - "https://www.googleapis.com/auth/compute"

machineDeployments:
- name: def00
  failureDomain: europe-west3-a
  instanceType: n2-standard-4
  replicas: 1
  rootVolumeSizeGB: 300
  customNodeLabels:
  - label=default
- name: def01
  failureDomain: europe-west3-b
  instanceType: n2-standard-4
  replicas: 1
  rootVolumeSizeGB: 300
  customNodeLabels:
  - label=default
- name: def02
  failureDomain: europe-west3-c
  instanceType: n2-standard-4
  replicas: 1
  rootVolumeSizeGB: 300
  customNodeLabels:
  - label=default

sshSSOPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4cvZ01fLmO9cJbWUj7sfF+NhECgy+Cl0bazSrZX7sU vault-ca@vault.operations.giantswarm.io"

# Used by `cluster-shared` library chart
includeClusterResourceSet: true
kubectlImage:
  registry: quay.io
  name: giantswarm/kubectl
  tag: 1.23.5

oidc:
  issuerUrl: ""
  caFile: ""
  clientId: ""
  usernameClaim: ""
  groupsClaim: ""
