clusterDescription: "test"  # Cluster description used in metadata.
organization: "test"  # Organization in which to create the cluster.
kubernetesVersion: 1.21.11
releaseVersion: 20.0.0-alpha1

gcp:
  baseImage: "https://www.googleapis.com/compute/v1/projects/capi-test-phoenix/global/images/cluster-api-ubuntu-1804-v1-20-10-1642604275"
  region: "europe-west6"
  project: "capi-test-phoenix"
  failureDomains:
  - "europe-west6-a"

network:
  autoCreateSubnetworks: true
  podCidr:
    - "192.168.0.0/16"

bastion:
  instanceType: n1-standard-2
  replicas: 1
  image: "https://www.googleapis.com/compute/v1/projects/capi-test-phoenix/global/images/cluster-api-ubuntu-1804-v1-20-10-1642604275"

controlPlane:
  instanceType: n1-standard-2
  replicas: 1  # Should be an odd number.
  rootVolumeSizeGB: 120

machineDeployments:
- name: def00
  failureDomain: europe-west6-a
  instanceType: n1-standard-2
  replicas: 3
  rootVolumeSizeGB: 300
  customNodeLabels:
  - label=default

sshSSOPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4cvZ01fLmO9cJbWUj7sfF+NhECgy+Cl0bazSrZX7sU vault-ca@vault.operations.giantswarm.io"
